export const MAX_VALID_LIMIT_ARG = 100

export const CATEGORY_FEATURE_COUNT = 3

export const PRODUCT_IN_CATEGORY_FEATURE_COUNT = 12

export const RECIPE_IN_CATEGORY_FEATURE_COUNT = 12

export const VIDEO_LIMIT = 12
export const VIDEO_ONE = 1