export const RESOLVER_FIND_BY_ID = 'findById'
export const RESOLVER_FIND_ONE = 'findOne'
export const RESOLVER_FIND_MANY = 'findMany'
export const RESOLVER_COUNT = 'count'
export const RESOLVER_CONNECTION = 'connection'
export const RESOLVER_PAGINATION = 'pagination'

export const RESOLVER_CREATE_ONE = 'createOne'
export const RESOLVER_CREATE_MANY = 'createMany'
export const RESOLVER_UPDATE_BY_ID = 'updateById'
export const RESOLVER_UPDATE_ONE = 'updateOne'
export const RESOLVER_UPDATE_MANY = 'updateMany'
export const RESOLVER_REMOVE_BY_ID = 'removeById'
export const RESOLVER_REMOVE_ONE = 'removeOne'
export const RESOLVER_REMOVE_MANY = 'removeMany'


// CUSTOM CATEGORY
export const RESOLVER_CATEGORY_FIND_MANY = 'categoryFindMany'
export const RESOLVER_CATEGORY_COUNT = 'categoryCount'

// CUSTOM RECIPE
export const RESOLVER_RECIPE_FIND_MANY = 'recipeFindMany'
export const RESOLVER_RECIPE_COUNT = 'recipeCount'

// CUSTOM HTML BLOCK
export const RESOLVER_HTML_BLOCK_FIND_MANY = 'htmlBlockFindMany'
export const RESOLVER_HTML_BLOCK_COUNT = 'htmlBlockCount'

// CUSTOM PRODUCT
export const RESOLVER_PRODUCT_FIND_MANY = 'productFindMany'
export const RESOLVER_PRODUCT_COUNT = 'productCount'

// CUSTOM BANNER
export const RESOLVER_BANNER_FIND_MANY = 'bannerFindMany'
export const RESOLVER_BANNER_COUNT = 'bannerCount'

export const RESOLVER_BANNER_GROUP_FIND_MANY = 'bannerGroupFindMany'
export const RESOLVER_BANNER_GROUP_COUNT = 'bannerGroupCount'

// CUSTOM PAGE
export const RESOLVER_PAGE_FIND_MANY = 'pageFindMany'
export const RESOLVER_PAGE_COUNT = 'pageCount'

// CUSTOM BLOG
export const RESOLVER_BLOG_FIND_MANY = 'blogFindMany'
export const RESOLVER_BLOG_COUNT = 'blogCount'

// CUSTOM RECRUITMENT
export const RESOLVER_RECRUITMENT_FIND_MANY = 'recruitmentFindMany'
export const RESOLVER_RECRUITMENT_COUNT = 'recruitmentCount'

// CUSTOM VIDEO
export const RESOLVER_VIDEO_FIND_MANY = 'videoFindMany'
export const RESOLVER_VIDEO_COUNT = 'videoCount'


export default {
  RESOLVER_FIND_BY_ID,
  RESOLVER_FIND_ONE,
  RESOLVER_FIND_MANY,
  RESOLVER_COUNT,
  RESOLVER_CONNECTION,
  RESOLVER_PAGINATION,

  RESOLVER_CREATE_ONE,
  RESOLVER_CREATE_MANY,
  RESOLVER_UPDATE_BY_ID,
  RESOLVER_UPDATE_ONE,
  RESOLVER_UPDATE_MANY,
  RESOLVER_REMOVE_BY_ID,
  RESOLVER_REMOVE_ONE,
  RESOLVER_REMOVE_MANY,

  RESOLVER_CATEGORY_FIND_MANY,
  RESOLVER_CATEGORY_COUNT,

  RESOLVER_RECIPE_FIND_MANY,
  RESOLVER_RECIPE_COUNT,

  RESOLVER_HTML_BLOCK_FIND_MANY,
  RESOLVER_HTML_BLOCK_COUNT,

  RESOLVER_PRODUCT_FIND_MANY,
  RESOLVER_PRODUCT_COUNT,

  RESOLVER_BANNER_FIND_MANY,
  RESOLVER_BANNER_COUNT,

  RESOLVER_BANNER_GROUP_FIND_MANY,
  RESOLVER_BANNER_GROUP_COUNT,

  RESOLVER_PAGE_FIND_MANY,
  RESOLVER_PAGE_COUNT,

  RESOLVER_BLOG_FIND_MANY,
  RESOLVER_BLOG_COUNT,

  RESOLVER_RECRUITMENT_FIND_MANY,
  RESOLVER_RECRUITMENT_COUNT,

  RESOLVER_VIDEO_FIND_MANY,
  RESOLVER_VIDEO_COUNT

}
